global:
  scrape_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']

  - job_name: 'dispatch-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['dispatch-service:8081']

  - job_name: 'driver-tracking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['driver-tracking-service:8082']

  - job_name: 'restaurant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['restaurant-service:8084']

